### ISSUE TITLE
ユーザープロフィール画像アップロードAPI

### ISSUE THREAD

**Issue by osakana9114** [yukihamu1206/twitter_last#22]
## 概要
S3に画像をアップロードするAPIの実装。
今回はこのアプリケーション内から [AWS SDK for PHP](https://aws.amazon.com/jp/sdk-for-php/) を使ってアップロードするようにしてみましょう。

　
### 設計
- [ ] リクエスト、レスポンス形式を決める

### 実装
- [ ] リクエスト内容のバリデーション処理（画像のサイズ）
- [ ] S3に画像をアップロードする
- [ ] 結果をjson形式で返す

**Comment by osakana9114** [comment]
@yukihamu1206 
ファイルアップロードのUIがちょっとややこしかったので、APIではなく一旦シンプルにすべて同期処理で実装するようにしましょうか。

灰色の部分はなしでこのようなかんじで！👇
![image](https://monosnap.com/image/NrrSb3xJbNOvqPAJG6n8NthwHkcWad)

**Comment by yukihamu1206** [comment]
> @yukihamu1206
> ファイルアップロードのUIがちょっとややこしかったので、APIではなく一旦シンプルにすべて同期処理で実装するようにしましょうか。
> 
> 灰色の部分はなしでこのようなかんじで！👇
> ![image](https://camo.githubusercontent.com/984d7e7506d8b5ebf1cb07c98c17330b4ce3f7b0/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f4e7272536233784a624e4f767150414a47366e384e746877486b63576164)

承知しました！ありがとうございます！

**Comment by osakana9114** [comment]
あと、ファイルの操作に今のところLaravelの `Storage` を利用しているので、とりあえずそちらで良いです。🍊
