### ISSUE TITLE
ユーザー詳細画面のページング

### ISSUE THREAD

**Issue by osakana9114** [yukihamu1206/twitter_last#25]
ユーザー詳細画面内、ユーザーのツイートのページングに不備があるようです。

![image](https://monosnap.com/image/cWxMDd0zyMZsvKdZRmEy33N3RZKw9P)

レビュー時に確認漏れていたのだと思いますが、全ツイートの数をページングの母数にしていることが原因です。

**Comment by osakana9114** [comment]
@yukihamu1206 
気付いたのでIssue立てておきました。
時間あればでいいので、また見てみてください🤖

**Comment by yukihamu1206** [comment]
> @yukihamu1206
> 気付いたのでIssue立てておきました。
> 時間あればでいいので、また見てみてください🤖

ありがとうございます！
