### ISSUE TITLE
ツイートの一覧表示

### ISSUE THREAD

**Issue by osakana9114** [yukihamu1206/twitter_last#8]
## 概要
ツイートの一覧を表示する機能の実装。
いいねボタンはまだなくて良いです。

　
### Model
- [x] ツイートテーブルの作成
- [x] アイコン画像保存用のS3バケット作成

### Controller, View
- [x] ツイートの一覧取得処理（ページングあり）
- [x] ツイートの一覧を同期処理で表示する

**Comment by osakana9114** [comment]
@yukihamu1206 
**tweets** テーブルの外部キーですが、migrationするとエラー出てました😵
```log
Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'tweets_user_id_foreign' are incompatible. (SQL: alter table `tweets` add constraint `tweets_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade on update cascade)
```

`id.users`はbigint型で、 `user_id.tweets` はint型とデータ型が異なっていることが原因です。
外部キー制約を付けるならデータ型を揃える必要があります。

これ👇とおなじパターンだと思われます
https://www.autovice.jp/articles/61

### 参考
[MySQL 8.0 リファレンスマニュアル > 13.1.20.6 外部キー制約の使用](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html)
> 外部キー定義は、次の条件に従います。
・外部キー内の対応するカラムと、参照されるキーは同様のデータ型を持っている必要があります。整数型のサイズと符号が同じである必要があります。文字列型の長さが同じである必要はありません。バイナリ以外の (文字の) 文字列カラムの場合、文字セットと照合順序が同じである必要があります。

**Comment by yukihamu1206** [comment]
【ページング】
indexで、eloquentを取得した後にforeachでいじっているので、
laravelのデフォルトのページングが使えず、やり方がわかりません。

```php
public function index(Tweet $tweet)
    {
        $tweets = Tweet::all();

        $lists = [];

        foreach($tweets as $tweet){
            $elm = [
                'text' => $tweet->text,
                'created_at' => $tweet->created_at->format('Y-m-d H:i'),
                'profile_image' => Storage::disk('s3')->url($tweet->user->profile_image ? $tweet->user->profile_image : 'noimage.jpg'),
                'name' => $tweet->user->name,
                'screen_name' => $tweet->user->screen_name,
                'user_id' => $tweet->user->id,
                'tweet_id' => $tweet->id
            ];

            $lists[] = $elm;
        }
```
【やってみたこと】
↓の記事を参考にして、
**https://qiita.com/Kazuki_i/items/b4215b12f27c1863477a**

LengthAwarePaginatorを使ってみましたが、viewの方で配列の中身がundefinedになります。
```php

       $lists = new LengthAwarePaginator(
         array_chunk($lists,5),
           count($lists),
           5,
           1
       );

        dd($lists);

        return view('tweets.index',['lists' => $lists]);
```

よろしくお願いいたします。
@osakana9114

**Comment by yukihamu1206** [comment]
データ型変更します！
@osakana9114

**Comment by osakana9114** [comment]
@yukihamu1206 
ページングについて、以下を参考にしてみました。
[Laravel 5.8 データベース：ペジネーション
](https://readouble.com/laravel/5.8/ja/pagination.html)

Model側にページ区切りのデータを返すメソッドを作ってみるといいかもしれません。
例： app/Models/Tweet.php
```php
/**
 * タイムラインの1ページに表示するツイートデータを取得する
 * 
 * @return array
 */
public function getTimeline()
{
    $tweets = self::paginate(5);

    $timeline = [];
    foreach ($tweets as $tweet) {
        $elm = [
            'text'          => $tweet->text,
            'created_at'    => $tweet->created_at->format('Y-m-d H:i'),
            'profile_image' => $tweet->user->profile_image ? $tweet->user->profile_image : 'noimage.jpg',
            'name'          => $tweet->user->name,
            'screen_name'   => $tweet->user->screen_name,
            'user_id'       => $tweet->user->id,
            'tweet_id'      => $tweet->id,
        ];

        $timeline[] = $elm;
    }

    return $timeline;
}
```

　
これをapp/Http/Controllers/TweetsController.phpで使用して、 LengthAwarePaginator() に適切なデータを渡してあげるといいかんじのページネーターを表示してくれるようです。
![iamge](https://monosnap.com/image/eWxbfQ0NpJyDm9BrQvADqum2AcHrfc)

**Comment by osakana9114** [comment]
@yukihamu1206 
### 補足
S3へのアクセス権限を付与したIAMユーザーですが、特定のバケットにのみアクセスを許可するように設定できます。
今の状態だと全てのバケットへのアクセス権限があるので、誤って別のバケットのオブジェクトを操作してしまう可能性を排除できません。
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

　
ポリシー（ `AmazonS3FullAccess` とかのやつ）は自分で定義することもできるので、以下のようにリソースを限定したポリシーを作成してIAMにアタッチします。
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::twitterlast"
        }
    ]
}
```
